name: Node CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and build
      run: |
        cd baseball-stadium && npm install
        cd baseball-stadium && npm run build --if-present
    - name: npm test
      run: |
        cd baseball-stadium && npm run actions-test
      env:
        CI: true
